version: 2

jobs:

  buildImage:
    docker:
      - image: web3f/ci-commons:v3
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.7
      - run:
          command: |
            /scripts/build-image.sh web3f/otree-academy-games .

  integrationTests:
    docker:
      - image: web3f/ci-commons:v3
    steps:
      - checkout
      - setup_remote_docker
      - run:
          description: run integration tests
          command: |
            /scripts/integration-tests.sh kindest/node:v1.23.13

  publishImage:
    docker:
      - image: web3f/ci-commons:v3
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            /scripts/publish-image.sh web3f/otree-academy-games

  deploy:
    environment:
      HELM_ENV: production
    docker:
      - image: web3f/ci-commons:v3
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            /scripts/deploy.sh -c community          

workflows:
  version: 2
  test_and_deploy:
    jobs:              
      - buildImage:
          context: dockerhub-bot
          filters:
            tags:
              only: /.*/
      - integrationTests:
          filters:
            tags:
              only: /.*/
          requires:
            - buildImage
      - publishImage:
          context: dockerhub-bot
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
          requires:
            - integrationTests
      - deploy:
          context: 
          - digital_ocean_access
          - vault_community
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
          requires:
            - publishImage
