environments:
  production:
  ci:
repositories:
  - name: w3f
    url: https://w3f.github.io/helm-charts
releases:
{{- if eq .Environment.Name "ci" }} 
  - name: otree
    chart: w3f/otree
    values:
      - ./config/otree-values.yaml.gotmpl
      - ./config/ci/otree-values.yaml.gotmpl
{{- end }}  

{{- if eq .Environment.Name "production" }} 
  - name: otree
    chart: w3f/otree
    version: ^v1.0.3
    namespace: otree-academy-games
    values:
      - ./config/otree-values.yaml.gotmpl
      - ./config/prod/otree-values.yaml.gotmpl
{{- end }}  